### ISSUE TITLE
src/common.bash: line 805: base_devel_missing: unbound variable

### ISSUE THREAD

**Issue by Novantix** [CyberShadow/aconfmgr#28]
Hi, I'm trying to backup my arch Linux config. However, I have ran into some errors while doing so.

I get the error:   :::::: Making sure the base-devel group is installed...
src/common.bash: line 805: base_devel_missing: unbound variable
::::::: Fatal error! Stack trace:

I am not sure what is wrong. I had a look at common.bash where the supposed unbound variable is, but I couldn't see any errors.

Also, may I ask, what are all the "missing files", and should I ignore these in 10-ignores.sh? 

This program saves just my configurations files made in arch Linux but not any other files right?

Thanks.

: Collecting data...
:: Compiling user configuration...
::: Using configuration in ./config
::: Sourcing ./config/10-ignore.sh...
::: Done (0 native packages, 0 foreign packages, 0 files).
:: Inspecting system state...
::: Querying package list...
:::: Done.
::: Enumerating managed files...
:::: Done.
::: Searching for lost files...
:::: Warning: reached 1000 lost files while in directory /boot/efi/EFI/Microsoft/Boot/et-EE.
::::: Perhaps add IgnorePath /boot/efi/EFI/Microsoft/Boot/et-EE/\* (or a parent directory) to configuration to ignore it.
:::: Scanning /usr/lib/python2.7/site-packages/twisted.:::: Done (2955 lost files).
::: Cleaning up ignored files' directories...
:::: Done.
::: Searching for modified files...
:::: Installing foreign dependency pacutils:
::::: Detecting AUR helper...
:::::: aurman... No
:::::: pacaur... No
:::::: yaourt... No
:::::: makepkg... Yes
::::: Building foreign package pacutils from source.
:::::: Using directory ./tmp/aur/pacutils.
:::::: Making sure the base-devel group is installed...
src/common.bash: line 805: base_devel_missing: unbound variable
::::::: Fatal error! Stack trace:
:::::::: src/common.bash:1 [AconfMakePkg]
:::::::: src/common.bash:1046 [AconfInstallForeign]
:::::::: src/common.bash:1067 [AconfNeedProgram]
:::::::: src/common.bash:326 [AconfCompileSystem]
:::::::: src/common.bash:718 [AconfCompile]
:::::::: src/save.bash:9 [AconfSave]
:::::::: src/main.bash:156 [Main]
:::::::: src/main.bash:173 [source]
:::::::: ./aconfmgr:26 [main]

**Comment by CyberShadow** [comment]
Should be fixed now.

**Comment by CyberShadow** [comment]
> Also, may I ask, what are all the "missing files", and should I ignore these in 10-ignores.sh?

Sorry, I don't know what you're referring to. `paccheck` mentions missing files in its output, when it finds a file that should be present as part of an installed package, but is absent from the filesystem; but aconfmgr doesn't use those terms, it uses "deleted files".

If this is what this is about, then I suggest you check why these files are absent. Perhaps a package was improperly removed, by deleting its files instead of using the package manager, or the installed package database is corrupt?

> This program saves just my configurations files made in arch Linux but not any other files right?

Conjecturally, yes, but it is up to the user to define which files are the configuration files and which are not.

**Comment by Novantix** [comment]
Hi thanks for taking the time to reply. It seems that nothing has changed, I still get the same exact error. git auto updates the repository when changes are made, right?

**Comment by CyberShadow** [comment]
> git auto updates the repository when changes are made, right?

Did you run `git pull`?

**Comment by Novantix** [comment]
Yep, I also rebooted to be sure. It appears that the error has shifted from line 805 to 806 with the unbound variable. 

Maybe the fix simply just shifted the error further down the chain?

: Collecting data...
:: Compiling user configuration...
::: Using configuration in ./config
::: Sourcing ./config/10-ignore.sh...
::: Done (0 native packages, 0 foreign packages, 0 files).
:: Inspecting system state...
::: Querying package list...
:::: Done.
::: Enumerating managed files...
:::: Done.
::: Searching for lost files...
:::: Warning: reached 1000 lost files while in directory /boot/efi/EFI
::::: Perhaps add IgnorePath /boot/efi/EFI/Microsoft/Boot/fi-FI/\* (or
:::: Done (2952 lost files).
::: Cleaning up ignored files' directories...
:::: Done.
::: Searching for modified files...
:::: Installing foreign dependency pacutils:
::::: Detecting AUR helper...
:::::: aurman... No
:::::: pacaur... No
:::::: yaourt... No
:::::: makepkg... Yes
::::: Building foreign package pacutils from source.
:::::: Using directory ./tmp/aur/pacutils.
:::::: Making sure the base-devel group is installed...
src/common.bash: line 806: base_devel_missing: unbound variable
::::::: Fatal error! Stack trace:
:::::::: src/common.bash:1 [AconfMakePkg]
:::::::: src/common.bash:1047 [AconfInstallForeign]
:::::::: src/common.bash:1068 [AconfNeedProgram]
:::::::: src/common.bash:326 [AconfCompileSystem]
:::::::: src/common.bash:718 [AconfCompile]
:::::::: src/save.bash:9 [AconfSave]
:::::::: src/main.bash:156 [Main]
:::::::: src/main.bash:173 [source]
:::::::: ./aconfmgr:26 [main]

**Comment by CyberShadow** [comment]
Oops, there was another bug on the same line. Pushed a second fix.

**Comment by Novantix** [comment]
Hey, I have a question. Not an issue, but what does the "Only in system: path/to/directory/*" prompts mean? Does the program ignore these directories/files or does it store them as a system backup?

For example: ::: Only in system: /usr/share/mime/text/x-moc.xml
::: Only in system: /usr/share/mime/text/x-modelica.xml
::: Only in system: /usr/share/mime/text/x-mof.xml
::: Only in system: /usr/share/mime/text/x-mpsub.xml
::: Only in system: /usr/share/mime/text/x-mrml.xml
::: Only in system: /usr/share/mime/text/x-ms-regedit.xml
::: Only in system: /usr/share/mime/text/x-mup.xml
::: Only in system: /usr/share/mime/text/x-nfo.xml
::: Only in system: /usr/share/mime/text/x-objcsrc.xml
::: Only in system: /usr/share/mime/text/x-ocaml.xml
::: Only in system: /usr/share/mime/text/x-ocl.xml
::: Only in system: /usr/share/mime/text/x-ooc.xml
::: Only in system: /usr/share/mime/text/x-opencl-src.xml
::: Only in system: /usr/share/mime/text/x-opml+xml.xml
::: Only in system: /usr/share/mime/text/x-pascal.xml
::: Only in system: /usr/share/mime/text/x-patch.xml
::: Only in system: /usr/share/mime/text/x-python.xml
::: Only in system: /usr/share/mime/text/x-python3.xml
::: Only in system: /usr/share/mime/text/x-qml.xml
::: Only in system: /usr/share/mime/text/x-readme.xml
::: Only in system: /usr/share/mime/text/x-reject.xml
::: Only in system: /usr/share/mime/text/x-rpm-spec.xml
::: Only in system: /usr/share/mime/text/x-sass.xml
::: Only in system: /usr/share/mime/text/x-scala.xml
::: Only in system: /usr/share/mime/text/x-scheme.xml
::: Only in system: /usr/share/mime/text/x-scons.xml
::: Only in system: /usr/share/mime/text/x-scss.xml
::: Only in system: /usr/share/mime/text/x-setext.xml
::: Only in system: /usr/share/mime/text/x-ssa.xml
::: Only in system: /usr/share/mime/text/x-subviewer.xml
::: Only in system: /usr/share/mime/text/x-svhdr.xml
::: Only in system: /usr/share/mime/text/x-svsrc.xml

Thanks.

**Comment by CyberShadow** [comment]
> what does the "Only in system: path/to/directory/*" prompts mean?

It means aconfmgr found a file that is neither owned by a package nor mentioned in the configuration (as a file or ignore rule).

> Does the program ignore these directories/files or does it store them as a system backup?

- `aconfmgr save` will copy and add the files to the configuration.
- `aconfmgr apply` will delete these files.

Or, you can use `IgnorePath` in your configuration to tell `aconfmgr` to pretend these files don't exist.
